blank_issues_enabled: false
contact_links:
  - name: ğŸš€ åŠŸèƒ½è¯·æ±‚
    url: https://github.com/Silentely/.github/issues/new?assignees=&labels=enhancement&template=feature_request.md
    about: å»ºè®®ä¸€ä¸ªæ–°åŠŸèƒ½æˆ–æ”¹è¿›
  - name: ğŸ› é”™è¯¯æŠ¥å‘Š
    url: https://github.com/Silentely/.github/issues/new?assignees=&labels=bug&template=bug_report.md
    about: æŠ¥å‘Šä¸€ä¸ªé”™è¯¯å¸®åŠ©æˆ‘ä»¬æ”¹è¿›